repos:
  - repo: https://github.com/Exabyte-io/pre-commit-hooks
    rev: 2023.6.28
    hooks:
      - id: ruff
        exclude: ^tests/fixtures*
      - id: black
        exclude: ^tests/fixtures*
      - id: isort
        exclude: ^tests/fixtures*
      - id: mypy
        exclude: ^tests/fixtures*
      - id: check-yaml
        exclude: ^tests/fixtures*
      - id: end-of-file-fixer
        exclude: ^tests/fixtures*
      - id: trailing-whitespace
        exclude: ^tests/fixtures*
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        language: node
        entry: npx lint-staged
        verbose: true # to see familiar lint-staged output
        pass_filenames: false # lint-staged has its own glob expression
